target:
  base_url: https://backend.dev-snorefox-wellness.diametos.com/api/v1/mobile/
  auth:
    type: bearer
    login_endpoint: /auth/sign-in
    username_field: email
    password_field: password
    token_field: accessToken
    credentials:
      email: test@example.com
      password: Test123!@#
  openapi:
    spec_path: swagger/biq.yml
    extract_endpoints: true
    use_spec_server_url: true
  simulate_server: false
  disable_fallback_endpoints: true
scanners:
- name: sql_injection
  enabled: false
- name: broken_authentication
  enabled: true
- name: broken_access_control
  enabled: true
- name: excessive_data_exposure
  enabled: true
- name: mass_assignment
  enabled: true
- name: unauthorized_password_change
  enabled: true
- name: unrestricted_account_creation
  enabled: true
- name: regex_dos
  enabled: false
- name: jwt_vulnerabilities
  enabled: true
  config:
    simulate_vulnerabilities: false
    debug: true
    login_endpoint: /auth/sign-in
    refresh_token_endpoint: /auth/refresh-tokens
    user_info_endpoint: /auth/check
    register_endpoint: /auth/sign-up
    username_field: email
    password_field: password
    access_token_field: accessToken
    refresh_token_field: refreshToken
