target:
  base_url: http://localhost:5002
  auth:
    type: none
  openapi:
    spec_path: /Users/rvance/Documents/scannerapi/swagger/openapi3.yml
    extract_endpoints: true
    use_spec_server_url: true
  simulate_server: false
  disable_fallback_endpoints: true
scanners:
- name: sql_injection
  enabled: true
  config:
    intensity: blind
    test_delay: 3.0
    max_tests_per_endpoint: 3
    continue_on_status_codes:
    - 200
    - 401
    - 422
    stop_on_first_vulnerability: true
- name: broken_authentication
  enabled: true
- name: broken_access_control
  enabled: true
- name: excessive_data_exposure
  enabled: true
- name: mass_assignment
  enabled: true
- name: unauthorized_password_change
  enabled: true
- name: unrestricted_account_creation
  enabled: true
- name: regex_dos
  enabled: false
- name: jwt_vulnerabilities
  enabled: true
  config:
    simulate_vulnerabilities: false
    debug: true
    login_endpoint: /users/v1/login
    user_info_endpoint: /
    register_endpoint: /users/v1/register
    username_field: email
    password_field: password
    access_token_field: accessToken
    refresh_token_field: refreshToken
